[custom]
;STASH订阅转换远程配置,需配合订阅转换网站使用
;https://github.com/GitHuber-Aegon/Clash/raw/main/config/ACL4SSR_STASH.ini
;不要随意改变关键字，否则可能会导致出错
;ACL4SSR规则

;去广告：支持
;自动测速：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;ruleset是分流规则,每个网址都有包含规则,可自行修改以符合自身使用习惯
;自定规则列表
ruleset=白名单,https://github.com/GitHuber-Aegon/Clash/raw/main/ruleslist/White.list
;ruleset=Netflix,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Netflix.list

;常用规则列表
ruleset=WeChat,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Wechat.list
ruleset=爱奇艺,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Iqiyi.list
ruleset=哔哩哔哩,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Bilibili.list
ruleset=哔哩哔哩,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/BilibiliHMT.list
ruleset=网易云音乐,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/NetEaseMusic.list
ruleset=Apple,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Apple.list
ruleset=Spotify,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Spotify.list
ruleset=Tinder,https://github.com/GitHuber-Aegon/Clash/raw/main/ruleslist/Tinder.list
ruleset=YouTube,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/YouTube.list
ruleset=X,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Twitter.list
ruleset=Telegram,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/Telegram.list
ruleset=AI,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/AI.list
ruleset=墙外世界,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyGFWlist.list
ruleset=墙外世界,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyLite.list
ruleset=墙外世界,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ProxyMedia.list
ruleset=墙外世界,https://github.com/GitHuber-Aegon/Clash/raw/main/ruleslist/Airport.list

;拒绝请求列表
ruleset=黑名单,https://github.com/BlueGrave/Clash/raw/master/Ruleset/AppleOS_Update.list
ruleset=黑名单,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanProgramAD.list
ruleset=黑名单,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanAD.list
;ruleset=黑名单,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyList.list
ruleset=黑名单,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyListChina.list
;ruleset=黑名单,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanEasyPrivacy.list

;直连请求列表
ruleset=墙内区域,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/GoogleCN.list
ruleset=墙内区域,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaDomain.list
ruleset=墙内区域,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaCompanyIp.list
ruleset=墙内区域,https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/Ruleset/ChinaDNS.list
ruleset=墙内区域,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

;以下是策略组,可根据自身需求作适当调整
;分流策略组(访问站点的分组)
;custom_proxy_group=Netflix`relay`⭕ 直连请求`[]🎯 默认选择`[]🇭🇰 香港
;custom_proxy_group=墙外世界`select`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=墙内区域`select`[]⭕ 直连请求`[]🚫 拒绝请求`[]🎯 默认选择`[]☑️ 手动切换
;custom_proxy_group=白名单`select`⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=黑名单`select`[]🚫 拒绝请求`⭕ 直连请求
;custom_proxy_group=黑名单`select`[]🚫 拒绝请求`⭕ 直连请求
;custom_proxy_group=WeChat`select`[]🇨🇳 中国大陆`[]🇭🇰 香港`[]🇹🇼 台湾`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=爱奇艺`select`[]🇨🇳 中国大陆`[]🇭🇰 香港`[]🇹🇼 台湾`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=哔哩哔哩`select`[]🇨🇳 中国大陆`[]🇭🇰 香港`[]🇹🇼 台湾`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=网易云音乐`select`[]🇨🇳 中国大陆`[]🇭🇰 香港`[]🇹🇼 台湾`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=Apple`select`[]🇨🇳 中国大陆`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=Spotify`select`[]🇨🇳 中国大陆`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=Tinder`select`[]🇨🇳 中国大陆`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=YouTube`select`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=X`select`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=Telegram`select`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=AI`select`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]🎯 默认选择`[]☑️ 手动切换`[]⭕ 直连请求`[]🚫 拒绝请求

;基础策略组
custom_proxy_group=📶 测速最佳`url-test`.*`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=🔙 故障转移`fallback`.*`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=♻️ 负载均衡`load-balance`.*`http://www.gstatic.com/generate_204`300,,2
custom_proxy_group=🎯 默认选择`select`[]📶 测速最佳`[]☑️ 手动切换`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]🇦🇺 澳洲`[]🌎 美洲`[]🇺🇸 美国`[]🇪🇺 欧洲`[]🌍 非洲`[]⭕ 直连请求`[]🚫 拒绝请求
custom_proxy_group=☑️ 手动切换`select`[]⭕ 直连请求`[]🚫 拒绝请求`.*
custom_proxy_group=🐟 漏网之鱼`select`[]⭕ 直连请求`[]🚫 拒绝请求`[]🎯 默认选择`[]☑️ 手动切换

;DIRECT`REJECT`美观组
custom_proxy_group=⭕ 直连请求`select`[]DIRECT`[]REJECT-DROP
custom_proxy_group=🚫 拒绝请求`select`[]REJECT-DROP`[]DIRECT

;节点分组(选择你的IP地区)
custom_proxy_group=🇨🇳 中国大陆`select`[]⭕ 直连请求`[]🚫 拒绝请求
;custom_proxy_group=🗺️ 地区选择`select`[]🇭🇰🇲🇴🇹🇼 港澳台`[]🌏 亚洲澳洲`[]🌎 美洲`[]🇪🇺 欧洲`[]🌍非洲
;custom_proxy_group=🇭🇰🇲🇴🇹🇼 港澳台`select`[]🇭🇰 香港`[]🇹🇼 台湾`(港|澳门|澳門|台|臺|HK|MO|TW)
;custom_proxy_group=🌏 亚洲`select`(亚洲|亞洲|日本|新加坡|韩|越|马|泰|印|菲|杜拜|埃及|斯坦|澳大利亚|新西兰)
;custom_proxy_group=🌎 美洲`select`(美国|加拿大|墨西哥|阿根廷|巴西|智利)
;custom_proxy_group=🇪🇺 欧洲`select`(欧洲|歐洲|德国|法国|瑞士|英国|波兰|意大利|西班牙|荷兰|俄罗斯|乌克兰|摩尔多瓦|土耳其)
;custom_proxy_group=🌍非洲`select`(非洲|尼日利亚)

;custom_proxy_group=🇭🇰🇲🇴🇹🇼 港澳台`url-test`(港|澳门|澳門|台|臺|HK|MO|TW)`http://www.gstatic.com/generate_204`300,,2
custom_proxy_group=🇭🇰 香港`url-test`(香港|HK|HongKong)`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=🇲🇴 澳门`url-test`(澳门|澳門|马交|馬交|MAC|Macau)`http://www.gstatic.com/generate_204`300,,2
custom_proxy_group=🇹🇼 台湾`url-test`(台|臺|新北|彰化|TW|TaiWan)`http://www.gstatic.com/generate_204`300,,2

custom_proxy_group=🌏 亚洲`url-test`(亚洲|亞洲|日本|新加坡|韩|越|柬|马来西亚|泰|印度|菲|印尼|亚美尼亚|格鲁吉亚|土耳其|沙特|伊拉克|以色列|阿曼|阿拉伯联合|卡塔尔|斯坦|杜拜|迪拜)`http://www.gstatic.com/generate_204`300,,2
custom_proxy_group=🇯🇵 日本`url-test`(日本|东京|東京|JP|Japan)`http://www.gstatic.com/generate_204`300,,2
custom_proxy_group=🇸🇬 狮城`url-test`(新加坡|狮城|獅城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,2
custom_proxy_group=🇰🇷 南韩`url-test`(韩|韓|KR|Korea)`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=🇻🇳 越南`url-test`(越南|VN|Vietnam)
;custom_proxy_group=🇰🇭 柬埔寨`url-test`(柬埔寨|KH|Cambodia)
;custom_proxy_group=🇲🇾 马来西亚`url-test`(马来西亚|馬來西亞|MY|Malaysia)
;custom_proxy_group=🇹🇭 泰国`url-test`(泰国|泰國|TH|Thai)
;custom_proxy_group=🇮🇳 印度`url-test`(印度|IN|India)
;custom_proxy_group=🇳🇵 尼泊尔`url-test`(尼泊尔|尼泊爾|NP|Nepal)
;custom_proxy_group=🇵🇭 菲律宾`url-test`(菲律宾|菲律賓|PH)
;custom_proxy_group=🇮🇩 印尼`url-test`(印尼|印度尼西亚|印度尼西亞|ID)
;custom_proxy_group=亚美尼亚
;custom_proxy_group=格鲁吉亚
;custom_proxy_group=土耳其
;custom_proxy_group=沙特阿拉伯
;custom_proxy_group=伊拉克
;custom_proxy_group=以色列
;custom_proxy_group=阿曼
;custom_proxy_group=阿拉伯联合酋长国
;custom_proxy_group=卡塔尔
;custom_proxy_group=🇵🇰 巴基斯坦`url-test`(巴基斯坦|PK)
;custom_proxy_group=🇺🇿 乌兹别克斯坦`url-test`(乌兹别克斯坦|UZ)
;custom_proxy_group=🇰🇿 哈萨克斯坦`url-test`(哈萨克斯坦|KZ)
;custom_proxy_group=🇦🇪 杜拜`url-test`(杜拜|迪拜|AE)

custom_proxy_group=🇦🇺 澳洲`url-test`(澳大利亚|澳大利亞|新西兰|新西蘭|纽西兰|紐西蘭|AU|AUS|Australia)`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=🇳🇿 新西兰`url-test`(新西兰|新西蘭|纽西兰|紐西蘭|NZ|NZL|New Zealand)

custom_proxy_group=🌎 美洲`url-test`(美国|加拿大|阿根廷|秘鲁|哥伦比亚|危地马拉|厄瓜多尔|哥斯达黎加|墨西哥|智利|玻利维亚|乌拉圭|巴西)`http://www.gstatic.com/generate_204`300,,2
custom_proxy_group=🇺🇸 美国`url-test`(美国|美利坚|US|USA)`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=🇺🇸 美国`url-test`(美|矽谷|硅谷|波特兰|达拉斯|俄勒冈|费利蒙|凤凰城|洛杉矶|圣何塞|西雅图|芝加哥|圣克拉拉|拉斯维加斯|US|USA)
;custom_proxy_group=🇨🇦 加拿大`url-test`(加拿大|CA|Canada)
;custom_proxy_group=🇦🇷 阿根廷`url-test`(阿根廷|AR)
;custom_proxy_group=秘鲁
;custom_proxy_group=哥伦比亚
;custom_proxy_group=危地马拉
;custom_proxy_group=厄瓜多尔
;custom_proxy_group=哥斯达黎加
;custom_proxy_group=🇲🇽 墨西哥`url-test`(墨西哥|MX)
;custom_proxy_group=🇨🇱 智利`url-test`(智利|CL)
;custom_proxy_group=玻利维亚
;custom_proxy_group=乌拉圭
;custom_proxy_group=🇧🇷 巴西`url-test`(巴西|BR)

custom_proxy_group=🇪🇺 欧洲`url-test`(欧洲|歐洲|德国|法国|瑞士|英国|爱尔兰|冰岛|波兰|意大利|西班牙|荷兰|芬兰|奥地利|立陶宛|瑞典|希腊|拉脱维亚|挪威|丹麦|比利时|卢森堡|马其顿|阿尔巴尼亚|葡萄牙|乌克兰|摩尔多瓦|爱沙尼亚|克罗地亚|斯洛文尼亚|俄罗斯|保加利亚|塞尔维亚|塞浦路斯)`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=🇩🇪 德国`url-test`(德国|德意志|DE|Deutschland)
;custom_proxy_group=🇫🇷 法国`url-test`(法国|FR)
;custom_proxy_group=🇨🇭 瑞士`url-test`(瑞士|CH)
;custom_proxy_group=🇬🇧 英国`url-test`(英国|英格兰|大不列颠|GB)
;custom_proxy_group=🇮🇪 爱尔兰`url-test`(爱尔兰|愛爾蘭|IE|Ireland)
;custom_proxy_group=🇮🇸 冰岛`url-test`(冰岛|冰島|IS|Iceland)
;custom_proxy_group=🇵🇱 波兰`url-test`(波兰|PL)
;custom_proxy_group=🇮🇹 意大利`url-test`(意大利|義大利|IT|Italy)
;custom_proxy_group=🇪🇸 西班牙`url-test`(西班牙|ES)
;custom_proxy_group=🇳🇱 荷兰`url-test`(荷兰|NL)
;custom_proxy_group=芬兰
;custom_proxy_group=奥地利
;custom_proxy_group=立陶宛
;custom_proxy_group=瑞典
;custom_proxy_group=希腊
;custom_proxy_group=拉脱维亚
;custom_proxy_group=挪威
;custom_proxy_group=丹麦
;custom_proxy_group=比利时
;custom_proxy_group=卢森堡
;custom_proxy_group=马其顿
;custom_proxy_group=阿尔巴尼亚
;custom_proxy_group=葡萄牙
;custom_proxy_group=🇺🇦 乌克兰`url-test`(乌克兰|UA)
;custom_proxy_group=摩尔多瓦
;custom_proxy_group=爱沙尼亚
;custom_proxy_group=克罗地亚
;custom_proxy_group=罗马尼亚
;custom_proxy_group=斯洛文尼亚
;custom_proxy_group=🇷🇺 俄罗斯`url-test`(俄罗斯|RU)
;custom_proxy_group=保加利亚
;custom_proxy_group=塞尔维亚
;custom_proxy_group=塞浦路斯

custom_proxy_group=🌍 非洲`url-test`(埃及|尼日利亚|摩洛哥|南非)`http://www.gstatic.com/generate_204`300,,2
;custom_proxy_group=埃及
;custom_proxy_group=🇳🇬 尼日利亚`url-test`(尼日利亚|NG)
;custom_proxy_group=摩洛哥
;custom_proxy_group=南非

enable_rule_generator=true
overwrite_original_rules=true

;Thanks = https://github.com/ACL4SSR/ACL4SSR/tree/master/Clash
