# 将proxy-providers里面链接中的“订阅链接”替换即可

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

subscribe-url: 订阅链接
#替换上面文字用于Stash获取机场流量信息并在主页显示

proxy-providers:
  All:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=订阅链接&emoji=true&list=true&udp=true"
    # 以下方法任选其一⚠️有Clash订阅优先使用方法二❗️
    # 1.可以使用任意类型的链接仅替换上面文字，多个链接使用英文符号的竖杠|隔开一起写上即可
    # 2.Sub-Store与Clash类型订阅链接替换掉整个引号""内的链接
    interval: 86400
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxies:
            
proxy-groups:
  - name: 墙外世界
    type: select
    proxies:
      - 🎯 默认选择
      - ☑️ 手动切换
      - ⭕ 直连请求
      - 🚫 拒绝请求
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/World_Map.png

  - name: 墙内区域
    type: select
    proxies:
      - ⭕ 直连请求
      - 🚫 拒绝请求
      - 🎯 默认选择
      - ☑️ 手动切换
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China_Map.png

  - name: 白名单
    type: select
    proxies:
      - ⭕ 直连请求
      - 🚫 拒绝请求
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/AdWhite.png

  - name: 黑名单
    type: select
    proxies:
      - 🚫 拒绝请求
      - ⭕ 直连请求
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/AdBlack.png
      
  - name: 📶 测速最佳
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    include-all: true

  - name: 🎯 默认选择
    type: select
    proxies:
      - 📶 测速最佳
      - ☑️ 手动切换
      - 🇭🇰 香港
      - 🇹🇼 台湾
      - 🌏 亚洲
      - 🇯🇵 日本
      - 🇸🇬 狮城
      - 🇰🇷 韩国
      - 🇦🇺 澳洲
      - 🌎 美洲
      - 🇺🇸 美国
      - 🇪🇺 欧洲
      - 🌍 非洲
      - 🎯 默认选择
      - ☑️ 手动切换
      - ⭕ 直连请求
      - 🚫 拒绝请求

  - name: ☑️ 手动切换
    type: select
        proxies:
      - ⭕ 直连请求
      - 🚫 拒绝请求
    include-all: true

  - name: 🐟 漏网之鱼
    type: select
        proxies:
      - ⭕ 直连请求
      - 🚫 拒绝请求
      - 🎯 默认选择
      - ☑️ 手动切换
    include-all: true

  - name: ⭕ 直连请求
    type: select
        proxies:
      - DIRECT
      - REJECT-DROP

  - name: 🚫 拒绝请求
    type: select
        proxies:
      - REJECT-DROP
      - DIRECT

  - name: 🇨🇳 中国大陆
    type: select
        proxies:
      - ⭕ 直连请求
      - 🚫 拒绝请求

  - name: 🇭🇰 香港
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    include-all: true
    filter: "🇭🇰|香港|HK|HongKong"
    icon: 

  - name: 🇹🇼 台湾
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    include-all: true
    filter: "🇹🇼|台湾|台灣|臺灣|TW|TaiWan"
    icon: 

rule-providers:  # 远程规则集
        
  YouTube:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Apple:
    type: http
    behavior: domain
    format: text
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.txt"
    path: ./ruleset/Apple.yaml
    interval: 86400

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  OtherProxy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Infatuation-Fei/rule/main/Clash/Rule/OtherProxy.yaml"
    path: ./ruleset/OtherProxy.yaml
    interval: 86400

  China:
    type: http
    behavior: domain
    format: text
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Domain.txt"
    path: ./ruleset/China.yaml
    interval: 86400

  Global:
    type: http
    behavior: domain
    format: text
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.txt"
    path: ./ruleset/Global-Domain.yaml
    interval: 86400

  Lan: # 局域网
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/lan.yaml
    interval: 86400

rules:
  - RULE-SET,China,WeChat
  - GEOIP,CN,国内网站,no-resolve
  - MATCH,🐟 漏网之鱼
