[custom]
;新枫之谷专用订阅转换远端模板

;新枫之谷规则
ruleset=🍄 TMS,https://raw.githubusercontent.com/GitHuber-Aegon/Clash/refs/heads/main/ruleslist/TMS.list
ruleset=🍊 Beanfun,https://raw.githubusercontent.com/GitHuber-Aegon/Clash/refs/heads/main/ruleslist/BeanfunHK.list
ruleset=🍊 Beanfun,https://raw.githubusercontent.com/GitHuber-Aegon/Clash/refs/heads/main/ruleslist/BeanfunTW.list

;其余直连
ruleset=🐟 漏网之鱼,[]FINAL

;策略组
custom_proxy_group=🍄 TMS`select`[]🇭🇰 香港`[]🇹🇼 台湾`(港|澳门|澳門|台|臺|HK|MO|TW)`[]DIRECT`[]REJECT
custom_proxy_group=🍊 Beanfun`select`[]🇭🇰 香港`[]🇹🇼 台湾`[]🌏 亚洲地区`[]🇯🇵 日本`[]🇸🇬 狮城`[]🇰🇷 南韩`[]DIRECT`[]REJECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]REJECT

;地区测速分组
;custom_proxy_group=🇭🇰🇲🇴🇹🇼 港澳台`url-test`(港|澳门|澳門|台|臺|HK|MO|TW)`http://www.gstatic.com/generate_204`60,,30
;custom_proxy_group=🇭🇰 香港全部`url-test`[]🇭🇰 香港游戏`[]🇭🇰 香港`http://www.gstatic.com/generate_204`60,,30
;custom_proxy_group=🇭🇰 香港游戏`url-test`^(?=.*(?:游戏|遊戲|Gaming))(?=.*(?:港|HK|HongKong)).*$`http://www.gstatic.com/generate_204`60,,30
custom_proxy_group=🇭🇰 香港`url-test`^(?!.*(?:游戏|遊戲|Gaming|BGP))(?=.*(?:港|HK|HongKong)).*$`http://www.gstatic.com/generate_204`60,,30
;custom_proxy_group=🇲🇴 澳门`url-test`(澳门|澳門||马交|MAC|Macau)`http://www.gstatic.com/generate_204`60,,30
custom_proxy_group=🇹🇼 台湾`url-test`(台|臺|新北|彰化|TW|TaiWan)`http://www.gstatic.com/generate_204`60,,30

custom_proxy_group=🌏 亚洲`url-test`(日本|新加坡|韩|越|柬|马来西亚|泰|印度|菲|印尼|亚美尼亚|格鲁吉亚|土耳其|沙特|伊拉克|以色列|阿曼|阿拉伯联合|卡塔尔|斯坦|杜拜|迪拜)`http://www.gstatic.com/generate_204`120,,10
custom_proxy_group=🇯🇵 日本`url-test`(日本|东京|東京|JP|Japan)`http://www.gstatic.com/generate_204`120,,10
custom_proxy_group=🇸🇬 狮城`url-test`(新加坡|狮城|獅城|SG|Singapore)`http://www.gstatic.com/generate_204`120,,10
custom_proxy_group=🇰🇷 南韩`url-test`(韩|韓|KR|Korea)`http://www.gstatic.com/generate_204`120,,10

enable_rule_generator=true
overwrite_original_rules=true
